### ISSUE TITLE
Automatic searching and scraping of reputable sources 

### ISSUE THREAD

**Issue by brennanpincardiff** [rlgbtq/TDoR2018#13]
Is it worth searching Twitter or other sources for reports/pictures/information which can then be checked and easily transferred?

**Comment by sefabey** [comment]
For Twitter, we need a keyword repo in multiple languages to scrape Twitter.

**Comment by hturner** [comment]
What format should this be in @sefabey? Is it okay to have a sub-folder here, or does it need to be in it's own repo?

**Comment by sefabey** [comment]
I'd say it's fine here. I'd prefer a tidy csv file for which I can update a
sample.

**Comment by annajayne** [comment]
Turning the list at https://github.com/rlgbtq/TDoR2018/issues/14 into a CSV file might be a good idea.

As translations are identified we can then add them to the file, and ultimately I can add it to the BitBucket repo.

**Comment by hturner** [comment]
I put the keywords in a CSV file as suggested, with some instructions for contributing translations. Existing rlgbtq collaborators can edit directly.

**Comment by hturner** [comment]
Will make this an issue for 2019 hackathon
