### ISSUE TITLE
Automatically update leaflet map when database is re-created

### ISSUE THREAD

**Issue by hturner** [rlgbtq/TDoR2018#15]
At the moment the global map in the slideshow on the homepage is just updated periodically.

It would be great to have a script that automatically updates the map (or creates a similar map) when the database is re-built.

**Comment by annajayne** [comment]
The map was generated using openstreetmap + leaflet and then cropped to fit the pins.

I haven't found a way to save a copy of the map and crop it appropriately, but I'm open to suggestions.

**Comment by annajayne** [comment]
Reposted to https://bitbucket.org/annajayne/tdor/issues/6/automatically-update-the-map-shown-on-the.

**Comment by hturner** [comment]
Possible issue for 2019 hackathon.
