### ISSUE TITLE
Add paragraph on tdor.translivesmatter.info to Wikipedia

### ISSUE THREAD

**Issue by hturner** [rlgbtq/TDoR2018#16]
Would be good to have a paragraph and link on https://en.wikipedia.org/wiki/Transgender_Day_of_Remembrance

**Comment by annajayne** [comment]
it would indeed. I can't really do it as I'm the author of the site, but anyone else can.

**Comment by hturner** [comment]
@DragonflyStats something you can help with?

**Comment by hturner** [comment]
Will make issue for 2019 hackathon.
