### ISSUE TITLE
Contact form for people to submit new reports/updates

### ISSUE THREAD

**Issue by hturner** [rlgbtq/TDoR2018#3]
A contact form could be added to the website for people to submit new reports/updates.

Desirable features:

- encryption to keep information private until it is verified
- captcha to avoid spam (should be accessible to visually impaired)
- related to separate email address with good spam protection (I know a provider we can ask who may provide a free one for a cause like this)
- structured to make it easy to merge with existing data files via a script (once verified)

**Comment by annajayne** [comment]
Reposted to https://bitbucket.org/annajayne/tdor/issues/1/add-contact-form-for-people-to-submit-new.

**Comment by hturner** [comment]
@annajayne I see this when I follow the link:

"We can't let you see this page
To access this page, you may need to log in with another account. You can also return to the previous page or go back to your dashboard."

Maybe you need to make the tracker public? Then we can put relevant issues there.

**Comment by annajayne** [comment]
Fixed now - for some reason the issue tracker on that repo (but not the data repo) was set to private.

**Comment by hturner** [comment]
Great, will close this here then.
