### ISSUE TITLE
Publishing the data for recent years as an R package

### ISSUE THREAD

**Issue by hturner** [rlgbtq/TDoR2018#5]
Currently there are two ways to access the data

1. Export as CSV for specific time period from website  - export also includes photos, thumbnails (with photo on transgender flag and short description), qr codes in separate folders.
2. Download monthly CSVs from Bitbucket repo.

An R package might

- Have an update for each TDoR period
- Contain combined CSV only? (links to permanent page for each individual)
- Vignette with example code to produce global summaries, e.g. maps etc

Questions

- Does this provide much value over existing facilities?
- Would it be better to wait until/unless website has JSON API and instead write a package to extract using the API for analysis?

**Comment by DaveParr** [comment]
starting on my fork

**Comment by brennanpincardiff** [comment]
Write vignette

**Comment by hturner** [comment]
Okay there is now a version on https://github.com/CaRdiffR/tdor with data for TDoR 2007 to 2018. There are still some things to tidy up (will add issues there) but it can now be tested and used in Paul's vignette.
