### ISSUE TITLE
Automated tweeting [was: Automating the generation of stand-alone memorial slideshows]

### ISSUE THREAD

**Issue by hturner** [rlgbtq/TDoR2018#6]
The website already offers memorial cards and and an HTML slideshow. The slideshow can be downloaded as a complete webpage, however this is not so portable as a PDF (print to PDF doesn't seem to work).

**Comment by annajayne** [comment]
I have the starting point for a Python script to do standalone memorial cards.

Print to PDF should work - that's how we've generated the cards for the Bournemouth vigil.

**Comment by hturner** [comment]
Yes, the memorial cards print to PDF very nicely, its the photo (thumbnail) slideshow I was referring to.

**Comment by brennanpincardiff** [comment]
It might be nice to have a GIF memorial slideshow that could be shared on social media. 
These could be names, photos, etc and could be separated by country perhaps.

**Comment by annajayne** [comment]
See also https://bitbucket.org/annajayne/tdor/issues/7/add-custom-tweet-fields-for-each-report.

**Comment by hturner** [comment]
The latest datasets now have a tweet field. Since @TDoRinfo regularly tweets out memorials I don't think a tweetbot is a priority. Will add GIF memorial slideshow as an idea for 2019 hackathon.
