### ISSUE TITLE
Creating infographics for TDoR 2018

### ISSUE THREAD

**Issue by hturner** [rlgbtq/TDoR2018#7]
Although TDoR emphasises remembering the individuals, infographics can help to show the scale of the issue and provide some sobering facts.

For 2016 and 2017, TMM have produced some infographics:
https://transrespect.org/wp-content/uploads/2017/11/TvT_TMM_TDoR2017_Infographics_EN.png
https://transrespect.org/wp-content/uploads/2016/11/TvT_TMM_TDoR2016_Infographics_EN.png

Potential areas for exploration

- Trends over time (TMM only look at 2015-2017)
- Causes of death in different regions
- Impact of political/legal changes

The style of graphics could also be something to consider - how suitable is it for sharing on Twitter or Facebook for example?

**Comment by brennanpincardiff** [comment]
Maybe some animations too?

**Comment by brennanpincardiff** [comment]
A few viz available [here](http://rpubs.com/brennanpincardiff/tdor_2018_3_viz).

**Comment by brennanpincardiff** [comment]
Some viz added to a vignette [here](https://github.com/brennanpincardiff/tdor/tree/master/vignettes) - could be improved, I feel sure. Pull request to [https://github.com/CaRdiffR/tdor] made.

**Comment by hturner** [comment]
Data now available in an R package for TDoR 2007 to 2018, see https://github.com/CaRdiffR/tdor. Please use this as the basis of any visualisations/infographics.

**Comment by hturner** [comment]
A few visualisations starting to come through from #TidyTuesday - will retweet on @R_Forwards if I see them (I expect @R_LGBTQ will pick them up too!) so keep an eye out for inspiration and to appreciate folks' contribution!

**Comment by hturner** [comment]
Will start a fresh issue on this for 2019
