### ISSUE TITLE
Creating a dashboard to explore the data

### ISSUE THREAD

**Issue by hturner** [rlgbtq/TDoR2018#8]
The website currently allows people to view filtered data as a map. 

A dashboard could be created to allow more interactive exploration of the data. Initially this could be based on a static version of the data, potentially in future this could use an API to display the latest data.

c.f. #7 on creating infographics.

**Comment by sastoudt** [comment]
Would a [Shiny Dashboard](https://rstudio.github.io/shinydashboard/index.html) be useful? It could be [included as part of the R package, be hosted separately, or both](https://deanattali.com/2015/04/21/r-package-shiny-app/). 

If you think this is the way to go, I could work on setting it up. If anyone has preferences for what the dashboard should look like/what features should be included, a checklist could be added to this issue to guide me.

**Comment by hturner** [comment]
Sounds good. It could be hosted on shinyapps.io and also put in the package.

I've invited you as a collaborator to https://github.com/CaRdiffR/tdor, I suggest you create a branch to work on this and create a pull request to the master branch when you have a first draft. 

For inspiration on the visualisations, you can see what's currently in the vignette and also #7 here.

**Comment by hturner** [comment]
Also invited you to this repo so you can assign yourself. Happy to add others that want to join in!

**Comment by hturner** [comment]
Thanks for your contribution @sastoudt! I will make adding your dashboard to the package a task for our 2019 hackathon (https://github.com/cardiffR/tdor2019).
