### ISSUE TITLE
Researching reports to add missing photos and other details

### ISSUE THREAD

**Issue by hturner** [rlgbtq/TDoR2018#9]
A photo and some background information about the person helps us to reflect on their lives, while news reports help us to validate the report of their death and understand more about the reasons behind it.

An on-going task is to fill the gaps in the database, c.f. #2.

**Comment by annajayne** [comment]
I'll be happy to give a quick overview of how to find and categorise news reports at the event, but you might find the following Facebook groups useful for research purposes as links many historic reports are archived there:

https://www.facebook.com/groups/1570448163283501/ (Trans Violence News)
https://www.facebook.com/groups/TransViolence/ (Transgender Violence)

If there were an easy way to archive the contents of these groups it would probably save a *lot* of legwork.

Primary sources outside the usual US/UK media which are worth knowing about include LGBT+ sites such as:

https://homofobiamata.wordpress.com/ (GGB - Brazil)
http://redetransbrasil.org.br/ (Rede Trans Brasil - Brazil)
http://agenciapresentes.org/ (Agencia Presentes - Argentina, Chile, Paraguay, Peru and Honduras)
http://www.pembehayat.org/ (Pembe Hayat - Turkey)
https://www.facebook.com/philtransmov/ (Association of Transgender People in the Philippines)
https://www.facebook.com/TransActionPak/ (Trans Action Pakistan)

These are just off the top of my head but one thing which might be useful would be to draw up a proper curated list and/or mine the data for stats on which sites/groups tend to yield source links.

**Comment by sefabey** [comment]
Working on checking and updating the cases from Turkey.

**Comment by annajayne** [comment]
I'm going to update the Readme.md file in the Bitbucket repo with more data on some of the primary sources. Details of potential search terms for different countries can also be added.

**Comment by annajayne** [comment]
I've collected quite a few links for review already, and from experience the best way to dead with them is to a) record them in a triage location, then b) collect them by month and then c) each out adding more detail as it is uncovered.

I just use a set of text files for this locally, but you could use a set of Google Docs (one per year, say) with a top level document providing linking and triage.

Some source links can cover multiple reports and more than one year, so it's important to be flexible and useful to identify where a source link may provide details such as a photo. The following are examples of a couple of sets of links I have recorded:

Kayden Clarke
Age 24
4 Feb 2016
EXISTING ENTRY - NEW LINKS

https://planettransgender.com/trans-man-with-aspergers-shot-dead-by-police-media-misgenders-deadnames/
https://www.azfamily.com/story/31141618/woman-dies-after-officer-involved-shooting-in-mesa/


William Lound
8 Feb 2016
2016_02_08_William-Lound.jpg

William's murder was not included on the official TGEU TDoR 2016 list.

(photo) https://www.manchestereveningnews.co.uk/news/greater-manchester-news/william-lound-killer-apologises-salford-11599018
https://www.manchestereveningnews.co.uk/news/greater-manchester-news/william-lound-stabbed-homophobic-hate-11600708
https://www.manchestereveningnews.co.uk/news/greater-manchester-news/william-lound-salford-university-death-10877361

**Comment by hturner** [comment]
Guidance on researching cases has been added to the Bitbucket repo: https://bitbucket.org/annajayne/tdor_data/src/default/
